// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnaxtnrzkzuzrkxcjyxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuYXh0bnJ6a3p1enJreGNqeXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODQ5OTQsImV4cCI6MjA3MTk2MDk5NH0.KjmDe19yy65fEE0u2Io4Tj14RiSmRbsPUHQvg9EP_so";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});